version: "3.3"
services:
  
  cachet:
    image: cachethq/docker:latest
    ports:
      - ":8000"
    #   - "8001:80"
    networks:
      - traefik
    environment:
      - APP_KEY=${APPSRV_CACHET_APP_KEY}
      #- APP_ENV=production
      #- APP_DEBUG=true
      - APP_URL=https://status.appsrv.com
      - APP_LOG=errorlog
      - DB_DRIVER=mysql
      - DB_HOST=${APPSRV_CACHET_MYSQL_HOSTNAME}
      - DB_DATABASE=${APPSRV_CACHET_MYSQL_DATABASE}
      - DB_USERNAME=${APPSRV_CACHET_MYSQL_USERNAME}
      - DB_PASSWORD=${APPSRV_CACHET_MYSQL_PASSWORD}
    deploy:
      replicas: 1
      restart_policy:
        delay: 10s
        max_attempts: 1
        window: 60s
      placement:
        constraints:
          - "node.role == manager"
      labels:
        - "traefik.port=8000"
        - "traefik.docker.network=traefik"
        - "traefik.backend=cachet"
        - "traefik.frontend.rule=Host:status.appsrv.com"
      
networks:
  traefik:
    external:
      name: traefik
