version: "3.3"
services:

  minio:
    image: minio/minio
    volumes:
      - minio-data:/export
      # - minio2-data:/export2
      # - minio3-data:/export3
      # - minio4-data:/export4
    # ports:
    #   - "9000:9000"
    networks:
      # - minio_distributed
      - traefik
    environment:
      - MINIO_ACCESS_KEY=${APPSRV_MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${APPSRV_MINIO_SECRET_KEY}
    deploy:
      replicas: 3
      restart_policy:
        delay: 10s
        max_attempts: 1
        window: 60s
      placement:
        constraints:
          - "node.role == manager"
      labels:
        - "traefik.port=9000"
        - "traefik.docker.network=traefik"
        - "traefik.backend=minio"
        - "traefik.frontend.rule=Host:minio.appsrv.com"
    command: server /export
    
  # minio1:
  #   image: minio/minio:RELEASE.2017-12-28T01-21-00Z
  #   volumes:
  #     - minio1-data:/export
  #   # ports:
  #   #   - "9001:9000"
  #   networks:
  #     # - minio_distributed
  #     - traefik
  #   environment:
  #     MINIO_ACCESS_KEY: AKIAIOSFODNN7EXAMPLE
  #     MINIO_SECRET_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
  #   deploy:
  #     restart_policy:
  #       delay: 10s
  #       max_attempts: 10
  #       window: 60s
  #     placement:
  #       constraints:
  #         - "node.role == manager"
  #     labels:
  #       - "traefik.port=9000"
  #       - "traefik.docker.network=traefik"
  #       - "traefik.backend=minio1"
  #       - "traefik.frontend.rule=Host:minio1.appsrv.com,minio.appsrv.com"
  #   command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export
  # 
  # minio2:
  #   image: minio/minio:RELEASE.2017-12-28T01-21-00Z
  #   volumes:
  #     - minio2-data:/export
  #   # ports:
  #   #   - "9002:9000"
  #   networks:
  #     - minio_distributed
  #     - traefik
  #   environment:
  #     MINIO_ACCESS_KEY: AKIAIOSFODNN7EXAMPLE
  #     MINIO_SECRET_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
  #   deploy:
  #     restart_policy:
  #       delay: 10s
  #       max_attempts: 10
  #       window: 60s
  #     placement:
  #       constraints:
  #         - "node.role == manager"
  #     labels:
  #       - "traefik.port=9000"
  #       - "traefik.docker.network=traefik"
  #       - "traefik.backend=minio2"
  #       - "traefik.frontend.rule=Host:minio2.appsrv.com,minio.appsrv.com"
  #   command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export
  
  # minio3:
  #   image: minio/minio:RELEASE.2017-12-28T01-21-00Z
  #   volumes:
  #     - minio3-data:/export
  #   # ports:
  #   #   - "9003:9000"
  #   networks:
  #     - minio_distributed
  #     - traefik
  #   environment:
  #     MINIO_ACCESS_KEY: AKIAIOSFODNN7EXAMPLE
  #     MINIO_SECRET_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
  #   deploy:
  #     restart_policy:
  #       delay: 10s
  #       max_attempts: 10
  #       window: 60s
  #     placement:
  #       constraints:
  #         - "node.role == manager"
  #     labels:
  #       - "traefik.port=9000"
  #       - "traefik.docker.network=traefik"
  #       - "traefik.backend=minio3"
  #       - "traefik.frontend.rule=Host:minio3.appsrv.com,minio.appsrv.com"
  #   command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export
  # 
  # minio4:
  #   image: minio/minio:RELEASE.2017-12-28T01-21-00Z
  #   volumes:
  #     - minio4-data:/export
  #   # ports:
  #   #   - "9004:9000"
  #   networks:
  #     - minio_distributed
  #     - traefik
  #   environment:
  #     MINIO_ACCESS_KEY: AKIAIOSFODNN7EXAMPLE
  #     MINIO_SECRET_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
  #   deploy:
  #     restart_policy:
  #       delay: 10s
  #       max_attempts: 10
  #       window: 60s
  #     placement:
  #       constraints:
  #         - "node.role == manager"
  #     labels:
  #       - "traefik.port=9000"
  #       - "traefik.docker.network=traefik"
  #       - "traefik.backend=minio4"
  #       - "traefik.frontend.rule=Host:minio4.appsrv.com,minio.appsrv.com"
  #   command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export

volumes:
  minio-data:
  # minio1-data:
  # minio2-data:
  # minio3-data:
  # minio4-data:

networks:
  minio_distributed:
    driver: overlay
  traefik:
    external:
      name: traefik
    