version: "3.3"
services:
  
  netdata:
    image: titpetric/netdata
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
    cap_add:
      - SYS_PTRACE
    networks:
      - traefik
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.role == manager"
      labels:
        - "traefik.port=19999"
        - "traefik.docker.network=traefik"
        - "traefik.backend=netdata"
        - "traefik.frontend.rule=Host:netdata.appsrv.com"

networks:
  traefik:
    external:
      name: traefik
    