version: "3.3"
services:
  traefik:
    image: traefik:latest
    ports:
      - "80:80"
      - "443:443"
      # web ui disabled
      #- "8080:8080"
    networks:
      - traefik
    environment:
      - NAMECHEAP_API_USER=${NAMECHEAP_API_USER}
      - NAMECHEAP_API_KEY=${NAMECHEAP_API_KEY}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/traefik/traefik.toml:/traefik.toml
      - /opt/traefik/acme.json:/acme.json
    deploy:
      restart_policy:
        condition: on-failure
      replicas: 1
      placement:
        constraints:
          - "node.role == manager"
          
networks:
  traefik:
    external:
      name: traefik
